-- AlterTable
ALTER TABLE "Gifts" ALTER COLUMN "price" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Supplier" ALTER COLUMN "contractedValue" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "amountPaid" SET DATA TYPE DOUBLE PRECISION;
